const lessonData = {};

lessonData["01_AlfredRedl.mp3"] = [{
    text: "1. Alfred Redl. Alfred Redl was a very high-ranking officer in the army of the Austro-Hungarian Empire. He was actually the head of the intelligence department. However, he had a dark secret: he was secretly working for the Russian Empire. Because he needed money for his private life, he sold the Russians his country’s entire plan for a war. This meant that when World War I started, the Russians knew exactly where the Austrian soldiers were going to move. Because of his betrayal, more than half a million Austrian soldiers died in the first months of the war. Redl also gave the names of many Austrian spies to the Russians, and those spies were executed. He was finally caught in 1913 when the police found secret letters with money. He committed suicide before he could be put on trial. He is remembered as one of history's most damaging traitors because his actions changed the history of Europe.",
    dict: { "high-ranking": "yüksek rütbeli", "intelligence": "istihbarat", "secretly": "gizlice", "entire": "bütün/tüm", "betrayal": "ihanet", "spies": "casuslar", "executed": "idam edildi", "suicide": "intihar", "trial": "duruşma/mahkeme", "damaging": "zarar verici", "traitors": "hainler" },
    questions: [ {q:"Was Alfred Redl a high-ranking officer?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he secretly work for the Russian Empire?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he sell his country's war plan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Russians know where the Austrian soldiers would move?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Russian spies help the Austrian army?", a_en:"No", a_tr:"Hayır"}, {q:"Was he caught when police found secret letters?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he commit suicide before his trial?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_AndreyVlasov.mp3"] = [{
    text: "2. Andrey Vlasov. Andrey Vlasov was a hero in the Soviet Union during the beginning of World War II. He was a very famous general who even helped defend Moscow from the German army. However, in 1942, he was captured by the Nazis. While he was a prisoner, he decided to change sides and work for Adolf Hitler. He helped create the 'Russian Liberation Army,' which was a group of Russian soldiers who fought for Germany against their own country. Vlasov told the Russians that they should join him to destroy the Soviet government. For the people of the Soviet Union, this was the ultimate betrayal. At the end of the war, Vlasov was captured by American soldiers and given back to the Soviet Union. He was put on trial in Moscow and executed in 1946. Even today, his name is a symbol of treason in Russia.",
    dict: { "hero": "kahraman", "defend": "savunmak", "captured": "esir alındı", "prisoner": "mahkum/esir", "liberation": "kurtuluş", "destroy": "yok etmek", "ultimate": "nihai/en büyük", "betrayal": "ihanet", "treason": "vatana ihanet" },
    questions: [ {q:"Was Andrey Vlasov a famous general at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help defend Moscow?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he captured by the Nazis in 1942?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he refuse to work for Adolf Hitler?", a_en:"No", a_tr:"Hayır"}, {q:"Did he create the Russian Liberation Army?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he given back to the Soviet Union at the end?", a_en:"Yes", a_tr:"Evet"}, {q:"Is his name a symbol of treason in Russia?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_BenedictArnold.mp3"] = [{
    text: "3. Benedict Arnold. Benedict Arnold was one of the greatest heroes of the American Revolution. He was a brave general who won many battles for the American rebels. However, he felt that the government did not respect him enough, and he needed more money. In 1780, he made a secret deal with the British. He was in charge of the fort at West Point, which was a very important military site. He planned to surrender the fort to the British army in exchange for a large amount of money and a job in the British army. His plan was discovered when a British spy was caught with Arnold’s secret papers. Arnold managed to escape to a British ship and lived the rest of his life in London. In America, his name is still used to describe someone who is a traitor to their friends or country.",
    dict: { "heroes": "kahramanlar", "rebels": "isyancılar", "respect": "saygı", "secret deal": "gizli anlaşma", "fort": "kale", "surrender": "teslim etmek/olmak", "exchange": "karşılığında", "discovered": "keşfedildi", "escape": "kaçmak", "describe": "tanımlamak" },
    questions: [ {q:"Was Benedict Arnold a brave general at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win many battles for the American rebels?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he feel the government respected him enough?", a_en:"No", a_tr:"Hayır"}, {q:"Did he plan to surrender West Point to the British?", a_en:"Yes", a_tr:"Evet"}, {q:"Was his plan discovered by the British army?", a_en:"No", a_tr:"Hayır"}, {q:"Did he manage to escape to a British ship?", a_en:"Yes", a_tr:"Evet"}, {q:"Is his name used to describe a traitor today?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_Brutus.mp3"] = [{
    text: "4. Marcus Brutus. Marcus Brutus was a close friend and protege of Julius Caesar, the leader of Rome. Caesar loved Brutus like a son and trusted him completely. However, Brutus became worried that Caesar wanted to become a king and destroy the Roman Republic. A group of politicians convinced Brutus that the only way to save Rome was to kill Caesar. On March 15, 44 BC, Brutus and a group of men attacked Caesar in the Senate building. According to legend, when Caesar saw Brutus with a knife, he said, 'You too, Brutus?' before he died. Brutus thought he was a hero for saving the Republic, but the people of Rome were very angry. A large civil war started, and Brutus eventually lost and killed himself. He is often considered the most famous traitor in history because he killed a man who truly loved and trusted him.",
    dict: { "protege": "korunan kişi/öğrenci", "trusted": "güvendi", "worried": "endişeli", "convinced": "ikna etti", "senate": "senato", "knife": "bıçak", "hero": "kahraman", "civil war": "iç savaş", "eventually": "sonunda", "truly": "gerçekten" },
    questions: [ {q:"Was Brutus a close friend of Julius Caesar?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Caesar trust Brutus completely?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Brutus want Caesar to become a king?", a_en:"No", a_tr:"Hayır"}, {q:"Did politicians convince Brutus to kill Caesar?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Brutus attack Caesar with a knife?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the people of Rome very happy about this?", a_en:"No", a_tr:"Hayır"}, {q:"Did Brutus kill a man who truly loved him?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_CharlesLee.mp3"] = [{
    text: "5. Charles Lee. Charles Lee was a high-ranking general in the American Continental Army during the Revolutionary War. He was very experienced, and many people thought he should have been the leader instead of George Washington. However, Lee was captured by the British in 1776. While he was a prisoner, he did something shocking: he wrote a detailed plan for the British on how to defeat the Americans. He told them where to attack and how to win the war quickly. When he was released and returned to the American army, he did not tell anyone what he had done. Later, during a major battle, he ordered his soldiers to retreat when they were winning. George Washington was very angry and removed him from the army. Years later, his secret papers for the British were found, proving that he was secretly working against the American cause while wearing an American uniform.",
    dict: { "experienced": "deneyimli", "instead of": "yerine", "shocking": "şok edici", "detailed": "detaylı", "defeat": "yenmek/mağlup etmek", "released": "serbest bırakıldı", "major": "büyük", "retreat": "geri çekilmek", "removed": "uzaklaştırdı", "proving": "kanıtlayarak" },
    questions: [ {q:"Was Charles Lee a high-ranking general?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he captured by the British in 1776?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he write a plan to defeat the Americans?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tell the Americans about his plan when he returned?", a_en:"No", a_tr:"Hayır"}, {q:"Did he order his soldiers to retreat during a battle?", a_en:"Yes", a_tr:"Evet"}, {q:"Was George Washington happy with his orders?", a_en:"No", a_tr:"Hayır"}, {q:"Were his secret papers found years later?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_DonaMarina.mp3"] = [{
    text: "6. Dona Marina. Dona Marina, also known as La Malinche, was an indigenous woman who played a vital role in the fall of the Aztec Empire. She was given as a slave to the Spanish explorer Hernan Cortes. She was very intelligent and quickly learned to speak Spanish. She became Cortes’s translator and his closest advisor. She helped him understand the politics of the different tribes and told him which groups hated the Aztecs. Because of her help, Cortes was able to build an army of thousands of native people to attack the Aztec capital. For many people in Mexico, she is a traitor who helped the foreigners destroy her own culture and people. However, others see her as a woman who was trying to survive in a very dangerous world. Today, her name is still used in Mexico to describe someone who prefers foreign things over their own.",
    dict: { "indigenous": "yerli", "vital role": "hayati rol", "slave": "köle", "translator": "çevirmen", "advisor": "danışman", "tribes": "kabileler", "native": "yerli", "foreigners": "yabancılar", "survive": "hayatta kalmak", "prefers": "tercih eder" },
    questions: [ {q:"Was Dona Marina an indigenous woman?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she given as a slave to Hernan Cortes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she become his translator and advisor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she tell Cortes which groups hated the Aztecs?", a_en:"Yes", a_tr:"Evet"}, {q:"Did her help stop Cortes from attacking the capital?", a_en:"No", a_tr:"Hayır"}, {q:"Do some people see her as a traitor?", a_en:"Yes", a_tr:"Evet"}, {q:"Is her name used to describe someone who loves their own culture?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["07_Ephialtes.mp3"] = [{
    text: "7. Ephialtes of Trachis. At the Battle of Thermopylae, a small group of Greeks led by King Leonidas was successfully holding a narrow mountain pass against a massive Persian army. The Persians could not get through, and it looked like the Greeks might win. However, a local man named Ephialtes saw a chance to get rich. He went to the Persian King and told him about a secret mountain path that went behind the Greek army. The Persians used this path and surrounded the Greeks. Because of his betrayal, the Greeks were defeated and King Leonidas and his 300 Spartans were all killed. Ephialtes expected a large reward, but he had to flee for his life because the Greeks wanted to kill him. His name became so hated in Ancient Greece that it eventually became a word for 'nightmare.' He is remembered as the man who destroyed the most famous defense in history for money.",
    dict: { "narrow": "dar", "mountain pass": "dağ geçidi", "get through": "geçmek", "secret": "gizli", "path": "patika/yol", "surrounded": "etrafını sardı", "defeated": "yenildi", "reward": "ödül", "flee": "kaçmak", "nightmare": "kabus", "defense": "savunma" },
    questions: [ {q:"Were the Greeks holding a narrow mountain pass?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Persians get through the pass easily at first?", a_en:"No", a_tr:"Hayır"}, {q:"Did Ephialtes want to get rich?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tell the Persian King about a secret path?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the Greeks surrounded and defeated?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Ephialtes get his large reward safely?", a_en:"No", a_tr:"Hayır"}, {q:"Did his name become a word for nightmare?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_Firouz.mp3"] = [{
    text: "8. Firouz. During the First Crusade, the Crusader army was trying to capture the massive city of Antioch. The city had giant walls, and the Crusaders were starving outside for many months. They could not get inside. However, an Armenian man named Firouz, who was in charge of a tower, was angry with his master in the city. He secretly contacted the Crusader leader and promised to open the tower at night. For a large amount of money, Firouz lowered a rope ladder, and the Crusaders climbed over the wall. They opened the gates and took the city. Because of Firouz's betrayal, the Crusaders survived and were able to continue their journey to Jerusalem. Firouz converted to Christianity and was given a title, but he was always remembered as a man who betrayed his city and his people for personal revenge and gold.",
    dict: { "crusade": "haçlı seferi", "capture": "ele geçirmek", "starving": "açlıktan ölmek", "secretly": "gizlice", "rope ladder": "ip merdiven", "climbed": "tırmandı", "gates": "kapılar", "survived": "hayatta kaldı", "converted": "din değiştirdi", "betrayed": "ihanet etti", "revenge": "intikam" },
    questions: [ {q:"Were the Crusaders trying to capture Antioch?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they starving outside the giant walls?", a_en:"Yes", a_tr:"Evet"}, {q:"Was Firouz happy with his master in the city?", a_en:"No", a_tr:"Hayır"}, {q:"Did he promise to open the tower at night?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lower a rope ladder for the Crusaders?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Crusaders take the city because of him?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he betray his city for personal revenge and gold?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_Ganelon.mp3"] = [{
    text: "9. Ganelon. Ganelon is a famous traitor from the legends of Charlemagne, the King of the Franks. According to the stories, Ganelon was a respected knight, but he hated his stepson, the hero Roland. When Charlemagne’s army was leaving Spain, Ganelon made a secret deal with the Moorish king. He told the enemy exactly when and where Roland and the rearguard of the army would be traveling through the mountains. Because of this information, the enemy attacked and killed Roland and all his men at the Battle of Roncevaux Pass. Ganelon tried to pretend he was innocent, but Charlemagne discovered the truth. Ganelon was put on trial and suffered a very violent execution. Although the story is partly legend, Ganelon became the symbol of the 'classic' traitor in European literature for hundreds of years. His name represents a person who lets their personal jealousy destroy a great hero and an army.",
    dict: { "legends": "efsaneler", "respected": "saygı duyulan", "knight": "şövalye", "stepson": "üvey oğul", "rearguard": "artçı birlik", "pretend": "gibi davranmak", "innocent": "masum", "discovered": "keşfetti", "execution": "idam", "represents": "temsil eder", "jealousy": "kıskançlık" },
    questions: [ {q:"Was Ganelon a respected knight at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he hate his stepson, Roland?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he make a secret deal with Charlemagne?", a_en:"No", a_tr:"Hayır"}, {q:"Did he tell the enemy where Roland would be traveling?", a_en:"Yes", a_tr:"Evet"}, {q:"Were Roland and his men killed?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Charlemagne discover the truth?", a_en:"Yes", a_tr:"Evet"}, {q:"Does his name represent personal jealousy today?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_GuyFawkes.mp3"] = [{
    text: "10. Guy Fawkes. Guy Fawkes was a soldier who was part of a secret group of English Catholics. They were very angry with King James I because they felt he was not treating Catholics fairly. They planned the 'Gunpowder Plot,' which was a plan to blow up the House of Parliament when the King and all the government leaders were inside. Guy Fawkes was the man chosen to hide in the cellar under the building with 36 barrels of gunpowder. He was waiting to light the fuse and destroy everything. However, a secret letter was sent to a government official warning them about the plot. The guards searched the cellars and found Fawkes just as he was preparing to start the explosion. He was arrested, tortured, and executed. Today, in England, people still celebrate 'Bonfire Night' every November 5th to remember that the traitor was caught and the King was saved.",
    dict: { "fairly": "adil bir şekilde", "plot": "komplo/plan", "blow up": "havaya uçurmak", "cellar": "mahzen/bodrum", "barrels": "variller", "gunpowder": "barut", "fuse": "fitil", "warning": "uyarı", "searched": "aradılar", "tortured": "işkence gördü", "celebrate": "kutlamak" },
    questions: [ {q:"Was Guy Fawkes angry with King James I?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they plan to blow up the House of Parliament?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he hiding in the cellar with gunpowder?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a secret letter warn the government?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the explosion happen?", a_en:"No", a_tr:"Hayır"}, {q:"Was Fawkes caught by the guards?", a_en:"Yes", a_tr:"Evet"}, {q:"Do people in England celebrate Bonfire Night today?", a_en:"Yes", a_tr:"Evet"} ]
}];lessonData["11_JeanBaptisteBernadotte.mp3"] = [{
    text: "11. Jean-Baptiste Bernadotte. Jean-Baptiste Bernadotte was one of the most successful generals for the French Emperor Napoleon. He was a brave soldier who won many battles. However, in 1810, he was surprisingly chosen to become the Crown Prince of Sweden. He moved to Sweden and changed his name. Napoleon thought he had a friend in Sweden, but Bernadotte had a different plan. He decided that Sweden’s interests were more important than his friendship with Napoleon. In 1813, he turned against France and joined the other European countries to fight against Napoleon. He used his knowledge of Napoleon’s tactics to help defeat the French army at the Battle of Leipzig. To Napoleon and the people of France, he was a great traitor. However, in Sweden, he is remembered as a great king who saved the country. His descendants still sit on the throne of Sweden today.",
    dict: { "successful": "başarılı", "brave": "cesur", "surprisingly": "şaşırtıcı bir şekilde", "Crown Prince": "veliaht prens", "interests": "çıkarlar", "friendship": "arkadaşlık", "turned against": "karşı döndü/cephe aldı", "tactics": "taktikler", "defeat": "yenmek/mağlup etmek", "descendants": "soyundan gelenler", "throne": "taht" },
    questions: [ {q:"Was Bernadotte a successful general for Napoleon?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he chosen to become the Crown Prince of Sweden?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he think his friendship with Napoleon was most important?", a_en:"No", a_tr:"Hayır"}, {q:"Did he turn against France in 1813?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help defeat the French army?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the people of France remember him as a hero?", a_en:"No", a_tr:"Hayır"}, {q:"Do his descendants still sit on the throne today?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_JudasIscariot.mp3"] = [{
    text: "12. Judas Iscariot. Judas Iscariot is perhaps the most famous traitor in the history of the world. He was one of the twelve disciples of Jesus. According to the Bible, he made a secret deal with the religious leaders who wanted to arrest Jesus. For thirty pieces of silver, Judas agreed to show them where Jesus was hiding. On the night of the arrest, Judas led a group of soldiers to a garden and identified Jesus by kissing him on the cheek. This is why the phrase 'the kiss of Judas' is used to describe an act of betrayal. Because of his actions, Jesus was arrested and eventually executed. Judas later felt terrible about what he had done and tried to give the money back, but it was too late. He eventually killed himself. His name is now a synonym for 'traitor' in almost every language in the world.",
    dict: { "perhaps": "belki de", "disciples": "havariler", "religious": "dini", "silver": "gümüş", "agreed": "kabul etti", "identified": "teşhis etti", "kissing": "öperek", "cheek": "yanak", "phrase": "ifade", "terrible": "korkunç", "synonym": "eşanlamlı" },
    questions: [ {q:"Is Judas Iscariot a famous traitor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he make a secret deal with religious leaders?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he agree to help them for thirty pieces of gold?", a_en:"No", a_tr:"Hayır"}, {q:"Did he identify Jesus by kissing him?", a_en:"Yes", a_tr:"Evet"}, {q:"Was Jesus arrested and executed?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Judas feel happy about what he had done?", a_en:"No", a_tr:"Hayır"}, {q:"Is his name a synonym for traitor today?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_MirJafar.mp3"] = [{
    text: "13. Mir Jafar. Mir Jafar was the commander of the army for the Nawab of Bengal, the ruler of a large part of India. During the Battle of Plassey, the British East India Company was trying to take control of the region. Mir Jafar made a secret deal with the British leader, Robert Clive. He promised that his part of the army would not fight during the battle. Because of his betrayal, the Nawab’s army lost, and the British won easily. In exchange, the British made Mir Jafar the new ruler, but he had no real power. This battle was the most important moment in Indian history because it allowed the British to begin their 200-year rule over the entire country. In India and Bangladesh, the name 'Mir Jafar' is still used today as a very strong insult to describe a traitor who sells his country to foreigners.",
    dict: { "commander": "komutan", "ruler": "hükümdar/yönetici", "region": "bölge", "promised": "söz verdi", "betrayal": "ihanet", "exchange": "karşılığında", "power": "güç", "moment": "an", "insult": "hakaret", "foreigners": "yabancılar" },
    questions: [ {q:"Was Mir Jafar the commander of the army?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the British try to take control of the region?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Mir Jafar make a secret deal with the British?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his army fight very hard during the battle?", a_en:"No", a_tr:"Hayır"}, {q:"Did the British win the battle easily?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the British give him real power later?", a_en:"No", a_tr:"Hayır"}, {q:"Is his name used as an insult today?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_PaullusVitellius.mp3"] = [{
    text: "14. Paullus Vitellius. Paullus Vitellius was a high-ranking Roman official and a friend of Germanicus, a very popular and famous Roman general. Germanicus was seen by many as the next great leader of Rome. However, he died mysteriously in the East, and many people believed he was poisoned by a rival named Piso. At first, Vitellius was one of the men who tried to find the truth and prosecute Piso for the murder. However, Vitellius later decided to betray the memory of his friend and his political group. He switched sides and became an informant for the Emperor Tiberius, who was suspicious of many Roman leaders. He gave the Emperor information that led to the arrest and death of many important men. Eventually, he was also accused of treason and died in prison. He is remembered as a man who betrayed his friends and his honor for political power and the favor of a suspicious emperor.",
    dict: { "official": "yetkili", "mysteriously": "gizemli bir şekilde", "poisoned": "zehirlendi", "rival": "rakip", "prosecute": "dava açmak/yargılamak", "memory": "anı/hatıra", "informant": "muhbir", "suspicious": "şüpheci", "accused": "suçlandı", "honor": "onur", "favor": "iyilik/lütuf" },
    questions: [ {q:"Was Vitellius a friend of Germanicus?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people think Germanicus was poisoned?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Vitellius always protect the memory of his friend?", a_en:"No", a_tr:"Hayır"}, {q:"Did he switch sides to become an informant?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his information lead to the death of important men?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Emperor trust him forever?", a_en:"No", a_tr:"Hayır"}, {q:"Did he die in prison?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_PhilippePetain.mp3"] = [{
    text: "15. Philippe Petain. Philippe Pétain was a massive hero in France during World War I. He was known as the 'Lion of Verdun' for his incredible bravery. However, during World War II, when the Nazi army invaded France, Pétain’s legacy changed forever. He became the leader of the French government and decided to surrender to Germany. He moved the capital to a city called Vichy and started to collaborate with the Nazis. His government helped the Germans arrest thousands of people, including Jews, and send them to concentration camps. After the war ended, Pétain was put on trial for treason. Many people in France felt that their greatest hero had become their greatest traitor. He was sentenced to death, but because he was very old, the sentence was changed to life in prison. He died in jail in 1951, remembered as a man who betrayed the freedom of France.",
    dict: { "bravery": "cesaret", "invaded": "işgal etti", "legacy": "miras", "surrender": "teslim olmak", "collaborate": "işbirliği yapmak", "concentration camps": "toplama kampları", "trial": "mahkeme/duruşma", "sentenced": "mahkum edildi", "freedom": "özgürlük" },
    questions: [ {q:"Was Philippe Pétain a hero during World War I?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he surrender to Germany in World War II?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he refuse to collaborate with the Nazis?", a_en:"No", a_tr:"Hayır"}, {q:"Did his government help the Germans arrest people?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he put on trial for treason after the war?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he executed immediately?", a_en:"No", a_tr:"Hayır"}, {q:"Did he die in jail?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_TridentineTraitors.mp3"] = [{
    text: "16. The Tridentine Traitors. During the 16th century, Europe was divided by religious wars between Catholics and Protestants. In the city of Trento, a group of high-level officials and messengers were caught in a major act of betrayal. They were secretly selling city secrets and political documents to the enemies of the Holy Roman Empire. This was a very dangerous time because the Council of Trent was meeting to decide the future of the Catholic Church. The traitors were found to be working for foreign powers and Protestant leaders who wanted to disrupt the meetings. Their actions could have caused a massive war and destroyed the peace of the region. When they were discovered, it caused a huge scandal across Europe. They were executed, and the story became a famous example of how individuals could betray their city and their faith for gold during a time of great religious conflict.",
    dict: { "divided": "bölünmüş", "religious": "dini", "messengers": "elçiler/haberciler", "act": "eylem", "decide": "karar vermek", "future": "gelecek", "foreign powers": "yabancı güçler", "disrupt": "bozmak/engel olmak", "scandal": "skandal", "faith": "inanç", "conflict": "çatışma" },
    questions: [ {q:"Was Europe divided by religious wars?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the officials selling secrets to enemies?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the Council of Trent meeting to decide the future?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the traitors work for the Holy Roman Empire?", a_en:"No", a_tr:"Hayır"}, {q:"Did their actions cause a huge scandal?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the traitors pardoned and sent home?", a_en:"No", a_tr:"Hayır"}, {q:"Were they executed for their crimes?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_VidkunQuisling.mp3"] = [{
    text: "17. Vidkun Quisling. Vidkun Quisling was a Norwegian politician who had a very extreme plan. In 1940, when the Nazis were preparing to invade Norway, Quisling secretly met with Adolf Hitler. He promised to help the Germans take control of his country. When the invasion started, Quisling went on the radio and declared himself the new leader of Norway. He told the Norwegian soldiers to stop fighting the Germans. His 'coup' failed at first, but the Nazis eventually made him the puppet leader of the country. He helped the Nazis arrest many Norwegians and send them to prison. After the war ended, he was arrested and executed for treason. His betrayal was so famous that his name, 'Quisling,' became a new word in the English language. Today, a 'quisling' is a person who helps an enemy take over their own country.",
    dict: { "politician": "politikacı", "extreme": "aşırı", "preparing": "hazırlanıyor", "invade": "işgal etmek", "declared": "ilan etti", "coup": "darbe", "failed": "başarısız oldu", "puppet": "kukla", "executed": "idam edildi", "enemy": "düşman", "take over": "devralmak/ele geçirmek" },
    questions: [ {q:"Was Vidkun Quisling a Norwegian politician?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he secretly meet with Adolf Hitler?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tell his soldiers to fight the Germans?", a_en:"No", a_tr:"Hayır"}, {q:"Did the Nazis make him the puppet leader?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help arrest many Norwegians?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he executed after the war?", a_en:"Yes", a_tr:"Evet"}, {q:"Is his name a new word in the English language?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_WangJingwei.mp3"] = [{
    text: "18. Wang Jingwei. Wang Jingwei was a very important leader in the Chinese government and a rival of Chiang Kai-shek. For a long time, he was a hero of the revolution. However, when Japan invaded China in 1937, Wang became convinced that China could not win the war. He decided that the best way to save the country was to cooperate with the invaders. In 1940, he moved to the city of Nanjing and became the leader of a puppet government that was controlled by Japan. He helped the Japanese rule over millions of Chinese people while the war was still going on. For the Chinese people, this was a massive betrayal. Wang died in Japan in 1944 before the war ended. After the war, the Chinese government destroyed his tomb to show that he was a traitor who should never be honored. He is remembered as a man who chose to serve the enemy instead of fighting for his country.",
    dict: { "rival": "rakip", "convinced": "ikna olmuş", "cooperate": "işbirliği yapmak", "invaders": "işgalciler", "puppet government": "kukla hükümet", "rule over": "yönetmek", "tomb": "mezar", "honored": "onurlandırıldı", "serve": "hizmet etmek", "instead of": "yerine" },
    questions: [ {q:"Was Wang a hero of the revolution at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he think China could win the war?", a_en:"No", a_tr:"Hayır"}, {q:"Did he cooperate with the Japanese invaders?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become the leader of a puppet government?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help the Japanese rule the Chinese people?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Chinese government build a statue for him?", a_en:"No", a_tr:"Hayır"}, {q:"Did they destroy his tomb after the war?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_WilliamJoyce.mp3"] = [{
    text: "19. William Joyce. William Joyce was an Irishman who was a fanatical supporter of the Nazis. Just before World War II started, he fled from Britain to Germany. He began a series of radio broadcasts from Berlin that were sent to the people of the United Kingdom. He was nicknamed 'Lord Haw-Haw' because of his strange and posh way of speaking. Every night, he told the British people that Germany was winning the war and that they should surrender. He used propaganda to try and make the British soldiers lose their courage. Although many people laughed at him, he was considered a very dangerous traitor. After the war ended, he was captured by British soldiers in a forest. Even though he was not a British citizen, he was put on trial for treason because he had a British passport. He was executed in London in 1946, the last person to be executed for treason in the UK.",
    dict: { "fanatical": "fanatik", "supporter": "destekçi", "fled": "kaçtı", "broadcasts": "yayınlar", "nicknamed": "lakap takıldı", "posh": "havalı/lüks", "propaganda": "propaganda", "courage": "cesaret", "citizen": "vatandaş", "passport": "pasaport" },
    questions: [ {q:"Was William Joyce a fanatical supporter of the Nazis?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he flee from Britain to Germany?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he send radio broadcasts from Berlin?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tell the British people they were winning?", a_en:"No", a_tr:"Hayır"}, {q:"Was he nicknamed Lord Haw-Haw?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he captured by British soldiers?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he executed in London?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_WuSangui.mp3"] = [{
    text: "20. Wu Sangui. Wu Sangui was a powerful general in the Ming Dynasty army in China. He was in charge of defending the Great Wall at the Shanhai Pass against the Manchu invaders from the north. However, a rebel group had captured the capital city of Beijing and killed the Emperor. Wu Sangui was angry and decided to make a deal with the enemy. He opened the gates of the Great Wall and allowed the Manchu army to enter China. Together, they defeated the rebels, but the Manchus then took control of the whole country and started the Qing Dynasty. By opening the gates, Wu Sangui allowed a foreign army to conquer his own country. He later tried to rebel against the Manchus, but it was too late. He is remembered in Chinese history as the man who let the invaders in and ended one of China’s greatest dynasties.",
    dict: { "defending": "savunmak", "invaders": "işgalciler", "rebel": "isyancı", "gates": "kapılar", "allowed": "izin verdi", "enter": "girmek", "defeated": "mağlup etti/yendi", "conquer": "fethetmek", "dynasties": "hanedanlıklar" },
    questions: [ {q:"Was Wu Sangui a powerful general?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he defending the Great Wall?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a rebel group capture the capital city?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he keep the gates of the Great Wall closed?", a_en:"No", a_tr:"Hayır"}, {q:"Did he allow the Manchu army to enter China?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Manchus take control of the whole country?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he succeed when he rebelled later?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["21_ZhangBangchang.mp3"] = [{
    text: "21. Zhang Bangchang. Zhang Bangchang was a high-level official in the Song Dynasty of China. In 1127, the Jin invaders from the north captured the capital city and the Emperor. The invaders did not want to rule the Chinese people directly at first, so they looked for a traitor to lead a 'puppet' government. They chose Zhang Bangchang. He agreed to become the Emperor of a new, fake country called 'Chu.' He helped the invaders control the Chinese people and collect money for the enemy army. Although he was only the leader for a very short time, his betrayal was a massive shock to the Chinese people. He was eventually captured by the Song loyalists and forced to commit suicide. He is remembered as one of the 'classic' traitors in Chinese history who sold his loyalty and his country for a fake title and a crown given by the enemy.",
    dict: { "official": "yetkili", "directly": "doğrudan", "fake": "sahte", "collect": "toplamak", "shock": "şok", "loyalists": "sadıklar", "commit suicide": "intihar etmek", "loyalty": "sadakat", "title": "unvan", "crown": "taç" },
    questions: [ {q:"Was Zhang Bangchang an official in the Song Dynasty?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Jin invaders capture the Emperor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the invaders want to rule directly at first?", a_en:"No", a_tr:"Hayır"}, {q:"Did Zhang agree to become the Emperor of a fake country?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help collect money for the enemy army?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he forced to commit suicide later?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he sell his loyalty for a fake title?", a_en:"Yes", a_tr:"Evet"} ]
}];
